# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b7da7a2a6b7cba1c0b9692b29395d3509c3aa2e975ae489950a27c1ca92bb4413ece77d84f70dde86b7f31d2d0e3c60d91801a5b527391ee26b5d542bc7dd89

test:
  secret_key_base: 8f721cca3565d3987693f38a20f76d972752f84658f938a3f5164699964111705c80f1751dfae538b9b36cf07fa7598c028fcd449d079c08e15cb5023dd951ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
